# Generated by Django 4.2.11 on 2024-05-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Nalog',
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nalog.basemodel')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
            bases=('nalog.basemodel',),
        ),
        migrations.CreateModel(
            name='Homeus',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nalog.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
            ],
            bases=('nalog.basemodel',),
        ),
    ]
