# Generated by Django 4.2.11 on 2024-05-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nalog', '0002_basemodel_delete_nalog_directors_homeus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homeus',
            new_name='Queue',
        ),
    ]
