# Generated by Django 4.2.11 on 2024-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalog', '0003_rename_homeus_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
