# Generated by Django 4.2.11 on 2024-05-05 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nalog', '0006_home_contact_delete_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_contact',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
